#!/usr/bin/env python3
"""P0 R19 -- bounded, read-only live Intel Worker release-truth preflight.

A PASS proves only the sampled Worker deployment/freshness/preview contract.
It never certifies historical dossier accuracy, private TLP retractions,
enterprise entitlements, billing, or customer production GO.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import re
import sys
import urllib.error
import urllib.parse
import urllib.request
from typing import Any, Callable

ORIGIN = "https://intel.cyberdudebivash.com"
MAX_AGE_SECONDS = 6 * 3600
CLOCK_SKEW_SECONDS = 120
HEX_SHA = re.compile(r"^[0-9a-f]{40}$")
STIX_ID = re.compile(
    r"^[a-z][a-z0-9]*(?:-[a-z0-9]+)*--"
    r"[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
)
INTERNAL_REPORT = re.compile(
    r"^(?:https://intel\.cyberdudebivash\.com)?/reports/", re.I
)


def _get_json(path: str) -> dict[str, Any]:
    # Paths are exclusively generated by this script from fixed local routes
    # and URL-quoted advisory keys. No user-supplied URL, credentials, writes,
    # redirects to foreign origins or unbounded response bodies are accepted.
    url = ORIGIN + path
    request = urllib.request.Request(url, headers={"Accept": "application/json",
                                                    "User-Agent": "SentinelAPEX-R19-ReadOnlyCert/1"})
    with urllib.request.urlopen(request, timeout=12) as response:
        if response.geturl().split("?", 1)[0].startswith(ORIGIN + "/") is False:
            raise ValueError("Unexpected external redirect")
        if response.status != 200:
            raise ValueError("Unexpected response status")
        raw = response.read(1024 * 1024 + 1)
    if len(raw) > 1024 * 1024:
        raise ValueError("Response exceeds bounded certification size")
    parsed = json.loads(raw)
    if not isinstance(parsed, dict):
        raise ValueError("Unexpected JSON document shape")
    return parsed


def _utc(value: Any) -> dt.datetime | None:
    if not isinstance(value, str):
        return None
    try:
        parsed = dt.datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        return None
    return parsed.astimezone(dt.timezone.utc) if parsed.tzinfo else None


def evaluate(
    expected_sha: str,
    get_json: Callable[[str], dict[str, Any]] = _get_json,
    *,
    now: dt.datetime | None = None,
    limit: int = 3,
) -> dict[str, Any]:
    """One finite set of GETs; codes only, no sensitive object/log values."""
    errors: list[str] = []
    checked = 0
    if not HEX_SHA.fullmatch(expected_sha or ""):
        return {"status": "BLOCKED", "reasons": ["EXPECTED_SHA_INVALID"],
                "preview_checked": 0}
    if limit < 1 or limit > 5:
        return {"status": "BLOCKED", "reasons": ["SAMPLE_BOUND_INVALID"],
                "preview_checked": 0}
    current = now or dt.datetime.now(dt.timezone.utc)
    if current.tzinfo is None:
        return {"status": "BLOCKED", "reasons": ["LOCAL_CLOCK_UNTRUSTED"],
                "preview_checked": 0}

    def fetch(path: str, reason: str) -> dict[str, Any]:
        try:
            value = get_json(path)
            if not isinstance(value, dict):
                raise ValueError("Non-object JSON")
            return value
        except (OSError, ValueError, TypeError, TimeoutError,
                urllib.error.URLError, json.JSONDecodeError):
            errors.append(reason)
            return {}

    live = fetch("/api/health/live", "LIVE_HEALTH_UNAVAILABLE")
    health = fetch("/api/health", "INTEL_HEALTH_UNAVAILABLE")
    preview = fetch(f"/api/preview?limit={limit}", "PREVIEW_UNAVAILABLE")

    if live.get("status") != "alive":
        errors.append("WORKER_NOT_ALIVE")
    if live.get("deploy_commit_sha") != expected_sha:
        errors.append("DEPLOYED_WORKER_SHA_MISMATCH")
    if health.get("status") != "ok" or health.get("checks", {}).get("publication_integrity") != "ok":
        errors.append("PUBLICATION_HEALTH_NOT_OK")
    intelligence = health.get("intelligence")
    if not isinstance(intelligence, dict):
        errors.append("INTELLIGENCE_HEALTH_MISSING")
    else:
        age = intelligence.get("age_seconds")
        max_age = intelligence.get("max_age_seconds")
        born = _utc(intelligence.get("generated_at"))
        if (intelligence.get("status") != "fresh"
                or type(age) is not int or type(max_age) is not int
                or age < 0 or max_age != MAX_AGE_SECONDS or age > MAX_AGE_SECONDS):
            errors.append("INTELLIGENCE_FRESHNESS_INVALID")
        if born is None or not -CLOCK_SKEW_SECONDS <= (current - born).total_seconds() <= MAX_AGE_SECONDS:
            errors.append("INTELLIGENCE_SOURCE_CLOCK_INVALID")

    pv = preview.get("preview")
    if preview.get("status") != "ok" or not isinstance(pv, dict):
        errors.append("PREVIEW_CONTRACT_MISSING")
    else:
        items = pv.get("items")
        if pv.get("publication_state") != "fresh" or pv.get("freshness_status") != "FRESH":
            errors.append("PREVIEW_NOT_FRESH")
        if not isinstance(items, list) or not items or len(items) > limit:
            errors.append("PREVIEW_ITEM_BOUND_INVALID")
        else:
            for item in items:
                checked += 1
                if not isinstance(item, dict):
                    errors.append("PREVIEW_ITEM_MALFORMED")
                    continue
                legacy = item.get("stix_id")
                is_stix = isinstance(legacy, str) and STIX_ID.fullmatch(legacy) is not None
                if (item.get("stix_id_kind") !=
                        ("STIX_2_1_SYNTAX_ONLY" if is_stix else "LEGACY_INTERNAL_IDENTIFIER")):
                    errors.append("LEGACY_STIX_KIND_INCORRECT")
                if (item.get("stix_object_id") != (legacy if is_stix else None)
                        or item.get("stix_object_id_validation") !=
                        ("SYNTAX_ONLY" if is_stix else "UNAVAILABLE")):
                    errors.append("STIX_FORMAT_DISCLOSURE_INVALID")
                if item.get("internal_advisory_id") != (item.get("id") or legacy):
                    errors.append("INTERNAL_ADVISORY_ID_MISMATCH")
                if item.get("tlp") != "TLP:CLEAR":
                    errors.append("PREVIEW_TLP_NOT_CLEAR")
                if item.get("report_customer_ready") is not True and item.get("report_customer_ready") is not False:
                    errors.append("REPORT_VERDICT_MISSING")
                    continue
                ready = item["report_customer_ready"]
                if item.get("report_publication_state") != ("CUSTOMER_READY" if ready else "BLOCKED"):
                    errors.append("REPORT_STATE_CONTRADICTORY")
                for key in ("blog_url", "report_url"):
                    v = item.get(key)
                    if not ready and isinstance(v, str) and INTERNAL_REPORT.match(v):
                        errors.append("BLOCKED_REPORT_LINK_EXPOSED")
                slug = item.get("id")
                if not isinstance(slug, str) or not re.fullmatch(r"intel--[a-zA-Z0-9_-]{1,100}", slug):
                    errors.append("ADVISORY_ID_INVALID")
                    continue
                authoritative = fetch(
                    "/api/v1/reports/" + urllib.parse.quote(slug, safe="") + "/publication-status",
                    "REPORT_STATUS_UNAVAILABLE"
                )
                if authoritative.get("report_id") != slug:
                    errors.append("REPORT_STATUS_ID_MISMATCH")
                if authoritative.get("customer_ready") is not ready:
                    errors.append("REPORT_VERDICT_DIVERGENCE")
                if ready and not any(
                    isinstance(item.get(k), str) and INTERNAL_REPORT.match(item[k])
                    for k in ("blog_url", "report_url")
                ):
                    errors.append("READY_REPORT_LINK_MISSING")
    return {"status": "LIVE_SLICE_VERIFIED_NOT_ENTERPRISE_GO" if not errors else "BLOCKED",
            "reasons": sorted(set(errors)), "preview_checked": checked}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--expected-worker-sha", required=True)
    parser.add_argument("--limit", type=int, default=3)
    args = parser.parse_args()
    result = evaluate(args.expected_worker_sha, limit=args.limit)
    print(json.dumps(result, sort_keys=True))
    return 0 if result["status"] == "LIVE_SLICE_VERIFIED_NOT_ENTERPRISE_GO" else 2


if __name__ == "__main__":
    sys.exit(main())
