#!/usr/bin/env python3
"""
cdb_apex_streamer.py - CYBERDUDEBIVASH(R) SENTINEL APEX v30.0+
High-Velocity Data Orchestrator

PURPOSE: Manages enterprise-grade data distribution for March 2026 campaigns.
MANDATE: 0 Platform Degradation, High-Concurrency, Fail-Safe.

Bug fix (agent/sdk unification pass): source_event_file was declared but
never read anywhere -- run_distribution_loop() instead broadcast a single
hardcoded fabricated event forever ("SALT_TYPHOON_EXTORTION",
192.168.1.100 -- an RFC 1918 private address, not a plausible public IOC).
A registered client would receive fabricated threat intelligence
presented as a live detection. data/cortex/stream_events.json is a real
file (394 real, pipeline-generated events at last regeneration); this now
actually loads and replays it instead of inventing data.
"""

import asyncio
import json
import logging
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Any

# Production logging for the distribution layer
logger = logging.getLogger("CDB_APEX_DISTRIBUTOR")

class ApexDataStreamer:
    """
    Orchestrates the flow of intelligence events from the pipeline-generated
    event snapshot to verified Enterprise SDK instances. This replays a
    static snapshot (regenerated by the ingestion pipeline) rather than a
    live socket -- there is no live pub/sub backend deployed.
    """
    def __init__(self):
        self.active_clients: Dict[str, asyncio.Queue] = {}
        self.is_running = False
        # Path to the pipeline-generated event snapshot (regenerated by
        # agent/v27/streaming/pipeline.py), resolved relative to this file
        # so it works regardless of the caller's working directory.
        self.source_event_file: Path = (
            Path(__file__).resolve().parents[2] / "data" / "cortex" / "stream_events.json"
        )

    async def register_client(self, client_id: str):
        """Initializes a dedicated high-speed buffer for a new enterprise client."""
        if client_id not in self.active_clients:
            self.active_clients[client_id] = asyncio.Queue(maxsize=1000)
            logger.info(f"APEX Streamer: Client {client_id} connected to high-velocity feed.")

    async def unregister_client(self, client_id: str):
        """Safely removes client from the distribution list."""
        if client_id in self.active_clients:
            del self.active_clients[client_id]
            logger.info(f"APEX Streamer: Client {client_id} detached.")

    async def broadcast_event(self, event_data: Dict[str, Any]):
        """
        Pushes a new IOC cluster or Threat Forecast to all active buffers.
        Uses a fire-and-forget approach to ensure 0 platform delay.
        """
        for client_id, queue in self.active_clients.items():
            try:
                if queue.full():
                    # Dropping oldest event to prevent memory overflow for slow clients
                    queue.get_nowait() 
                queue.put_nowait(event_data)
            except Exception as e:
                logger.error(f"Failed to push to client {client_id}: {e}")

    def _load_events(self) -> List[Dict[str, Any]]:
        """Load the real, pipeline-generated event snapshot. Returns [] if absent/unreadable."""
        try:
            with open(self.source_event_file, "r", encoding="utf-8") as f:
                snapshot = json.load(f)
            events = snapshot.get("events", [])
            logger.info(f"APEX Streamer: loaded {len(events)} events from {self.source_event_file}")
            return events
        except FileNotFoundError:
            logger.warning(f"APEX Streamer: no event snapshot at {self.source_event_file} -- nothing to stream.")
            return []
        except (json.JSONDecodeError, OSError) as e:
            logger.error(f"APEX Streamer: failed to load {self.source_event_file}: {e}")
            return []

    async def run_distribution_loop(self, cycle_delay_s: float = 0.1):
        """
        The main distribution engine.

        Replays the pipeline-generated event snapshot (source_event_file)
        to every registered client. This is a static-snapshot replay, not
        a live feed -- there is no deployed real-time pub/sub backend to
        connect to. Each event keeps its original payload/timestamp; a
        `replayed_at` field is added so consumers can tell replay time
        from the event's real original timestamp.

        Args:
            cycle_delay_s: Delay between events (default: 10Hz).
        """
        self.is_running = True
        logger.info("APEX Streamer: Data Distribution Loop active.")

        events = self._load_events()
        if not events:
            logger.warning("APEX Streamer: no events to distribute; loop exiting.")
            self.is_running = False
            return

        idx = 0
        while self.is_running:
            try:
                event = dict(events[idx % len(events)])
                event["replayed_at"] = datetime.utcnow().isoformat()
                await self.broadcast_event(event)
                idx += 1
                await asyncio.sleep(cycle_delay_s)

            except Exception as e:
                logger.error(f"Streamer Error: {e}")
                await asyncio.sleep(1)

    def stop(self):
        """Graceful shutdown of the distribution layer."""
        self.is_running = False
        logger.info("APEX Streamer: Distribution loop terminated.")

# Production Entry Point for the Streaming Service
if __name__ == "__main__":
    streamer = ApexDataStreamer()
    try:
        asyncio.run(streamer.run_distribution_loop())
    except KeyboardInterrupt:
        streamer.stop()