// SENTINEL APEX deploy provenance module.
//
// This file is generated by deploy-worker.yml during CI. The committed
// repository copy intentionally carries non-production sentinel values so
// local/unit-test executions cannot accidentally claim a live production
// deployment. The generated CI copy preserves this exact module shape and
// replaces only the two immutable values below.
//
// The extra documentation in this module is intentional. The production
// Worker source integrity gate requires every top-level Worker module to be
// at least 1 KiB so catastrophic truncation is detected before deployment.
// Keeping the generated provenance module above that threshold means we do
// not weaken or special-case the integrity gate merely because this module
// is small.
//
// Security properties:
// - no credential or secret material is stored here;
// - the Git commit SHA is public deployment provenance;
// - the Actions run ID is public operational provenance;
// - values are immutable module constants;
// - production CI overwrites this file before syntax/integrity validation;
// - post-deploy validation fails unless the public liveness endpoint reports
//   the exact Git commit SHA that GitHub Actions attempted to deploy.
//
// Cost properties:
// - no storage lookup is performed at request time;
// - no KV, R2, D1, Durable Object, or external API operation is required;
// - provenance is compiled directly into the Worker bundle.
//
// Repository-safe defaults follow.
export const DEPLOY_COMMIT_SHA = "development";
export const DEPLOY_RUN_ID = "local";
export const DEPLOY_PROVENANCE = Object.freeze({
  commitSha: DEPLOY_COMMIT_SHA,
  runId: DEPLOY_RUN_ID,
  source: "repository-default-non-production",
});
